apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-access-from-webdb
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongodb     
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webdb  
    ports:
    - port: {{ .Values.ports.mongodb }}
      protocol: TCP