apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: aloussaief
type: Opaque
data:
  root-username: {{ .Values.mongodb.rootUsername | b64enc }}
  root-password: {{ .Values.mongodb.rootPassword | b64enc }}