apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  rs-init.sh: |
    #!/bin/bash
    mongosh --host mongodb-0.mongodb.aloussaief.svc.cluster.local --eval "rs.initiate({
      _id: '{{ .Values.mongodb.replicaSetName }}',
      members: [
        { _id: 0, host: 'mongodb-0.mongodb.aloussaief.svc.cluster.local:27017' },
        { _id: 1, host: 'mongodb-1.mongodb.aloussaief.svc.cluster.local:27017' },
        { _id: 2, host: 'mongodb-2.mongodb.aloussaief.svc.cluster.local:27017' }
      ]
    })"